### PR TITLE
improved UI

### PR DESCRIPTION
**Pull request by sairajchouhan**
Hey @iampavangandhi I have made some UI design changes that were most important. detailed information of what and why the changes are made is in the pdf [here](https://firebasestorage.googleapis.com/v0/b/portfolio-e0fa5.appspot.com/o/contrib.pdf?alt=media&token=a1fd444e-0497-4e7b-b3f1-ef40626f12ce)

### CODE REVIEW

**Comment by iampavangandhi** [comment]
@sairaj2119 pdf is not accessible. showing 404 error

**Comment by sairajchouhan** [comment]
> @sairaj2119 pdf is not accessible. showing 404 error

check it now again

**Comment by iampavangandhi** [comment]
@sairaj2119 great work :+1: but there are still some UI issues in the contact form (in mobile layout as well as web layout) can you improve that also. You can also experiment in that if you want.

**Comment by sairajchouhan** [comment]
Sorry dude I am a little busy with freelancing I will definitely contribute
I find some play time

**Pull request merged**
